jest.config.js, package-lock.json, package.json, src/authorization.ts, src/constants.ts, src/transaction.ts, tests/src/contracts/kv-store.clar, tests/src/index-tests.ts
This PR updates the `contract deploy` test and adds a test for `contract-call` transaction serialization.
It includes a few fixes for `txid` generation which was breaking Transaction signing. It also fixes the values in the `PayloadType` enum, accounting for a typo in SIP 005 which has been fixed (https://github.com/blockstack/stacks-blockchain/pull/1326)
Additionally, I moved the `collectCoverage` option out of the Jest config and into `package.json`, as it was breaking my VSCode debugger (https://github.com/kulshekhar/ts-jest/issues/484)
=> Contract transaction tests

README.md, package-lock.json, src/authorization.ts, src/builders.ts, src/clarity/clarityTypes.ts, src/payload.ts, src/postcondition.ts, src/utils.ts, tests/src/index-tests.ts
This PR switches from BigInt to bn.js throughout to improve compatibility.
=> refactor: use bn.js instead of BigInt

src/authorization.ts, src/clarity/clarityTypes.ts, src/payload.ts, src/postcondition.ts
The way `bn.js` implements `toBuffer` is problematic for web environments. It tries to `require('buffer')`, which doesn't play well in web environments. However, it's easy to add a global `Buffer` as a polyfill. When using a global polyfill, we need to use `toArrayLike(Buffer, ...)` instead of `toBuffer`. This will work much better in web environments.
Note: These changes do not include the ESLint setup from #27. We should merge that first, and then fix any merge this PR.
=> fix: use toArrayLike instead of toBuffer

src/authorization.ts, src/keys.ts, src/payload.ts, src/transaction.ts, src/types.ts
I've been running into intermittent invalid private key generation. The problem was a BN.js `toString('hex')` call not performing any padding. 
The following test could trigger the error in the previous code:
```ts
test('Stacks key generation', () => {
for (let i = 0; i < 1000; i++) {
StacksPrivateKey.makeRandom();
}
});
```
This would often result in 63-char length keys like:
`9aa98e0581c44ca257519215f3a8246fbe6f659dede388c147bacc8f2960986` vs the correct result:
`09aa98e0581c44ca257519215f3a8246fbe6f659dede388c147bacc8f2960986`
Also added error handling to several conditionals that would silently fail or result in hard to track down errors later on.
=> fix: invalid private key length generated from `StacksPrivateKey.makeRandom`

src/authorization.ts, src/builders.ts, src/keys.ts, src/payload.ts, src/transaction.ts, src/types.ts, tests/src/builder-tests.ts
Use the following template to create your pull request
Make specifying post-condition fields in tx builders consistent. Example of new usage:
```ts
const tx = makeSmartContractDeploy(<args>, {
postConditions: myConditions,
postConditionsMode: PostConditionMode.Allow,
}).serialize();
```
Previously, this required modifying a property on the intermediate tx object before serialization.
=> feat: add support for specifying post-condition mode

README.md, package-lock.json, src/authorization.ts, src/builders.ts, src/transaction.ts, tests/src/authorization-tests.ts, tests/src/builder-tests.ts, tests/src/transaction-tests.ts
This PR changes all references of fee "rate" to a total fee. This brings it in line with what's actually implemented on core. The wire format specified in [SIP005](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-005-blocks-and-transactions.md#transaction-encoding) needs to be updated as well. This change is needed because downstream integrations erroneously input a fee rate per byte instead of a total fee when building transactions, leading to the transaction being rejected for having a fee that's too low. 
Related to: 
https://github.com/blockstack/stacks-transactions-js/issues/55
https://github.com/blockstack/stacks-transactions-js/issues/54
Not a breaking change.
Yes
Transactions built with the lib should continue to function when the fee is set correctly.
=> Change all references of transaction fee rate to a total fee

README.md, src/builders.ts, src/index.ts, src/network.ts, src/transaction.ts, tests/src/builder-tests.ts, tests/src/transaction-tests.ts
This PR adds the network options object to transaction builder functions. Networks are constants that will determine the transaction version, chain ID and API URLs. This simplifies the builder options and provides defaults. This PR also moves the `broadcast()` function out of the `StacksTransaction` class and into a separate function in the tx builders. This is so that users can use a network object to specify broadcast API URLs. This PR is based off of the fee estimate PR: #45 
```javascript
const network = new StacksTestnet();
const options = {
network: network
};
const transaction = await makeSTXTokenTransfer(
recipientAddress,
amount,
secretKey,
options
);
broadcastTransaction(transaction, network);
```
```javascript
const myNetwork = {
version: TransactionVersion.Mainnet;
chainId: …
```
=> Use network object in tx builder options

src/builders.ts, src/postcondition.ts, src/types.ts, tests/src/postcondition-tests.ts
Improves the DX for creating a post-conditions. Previously, several functions had to be discovered (e.g. `makeStandardNonFungiblePostCondition`, `makeContractNonFungiblePostCondition`, `createNonFungiblePostCondition`, `createAssetInfo`).
And the resulting code pretty verbose:
```ts
const postCondition = createNonFungiblePostCondition(
createContractPrincipal(
'SP2JXKMSH007NPYAQHKJPQMAQYAD90NQGTVJVQ02B', 
'contract-name'),
NonFungibleConditionCode.Owns,
createAssetInfo('SP2ZP4GJDZJ1FDHTQ963F0292PE9J9752TZJ68F21', 
'contract_name', 
'asset_name'),
bufferCVFromString('nft_asset_name')
);
// Note: more verbose when the inputs are strings that need to be split
// (e.g. `SP2JXKMSH007NPYAQHKJPQMAQYAD90NQGTVJVQ02B.contract-name`)
```
These post conditions can now be constructed without …
=> Support strings for contract principals and asset info IDs

package.json, tsconfig.build.json
Use the npm `prepare` script to make this lib usable when installed as a git dependency. This lib is under rapid development, and blocks staging deployments for dependent projects when a branch has not been merged & published to NPM. 
Additionally, this PR fixes the nested build output directory e.g. 
`@blockstack/stacks-transactions/lib/src/bufferReader` vs
`@blockstack/stacks-transactions/lib/bufferReader`
This was simply the build script missing a `tsconfig.build.json` param which excludes the `tests` dir from the output.
=> Add prepare script for git installs, fix build directory structure

src/authorization.ts
Fix pub key encoding hex value not properly converted to string for sig hash.
Potential fix for #58 
No
No
Transaction generation should now work in browsers
For detailed steps to reproduce, see #58
=> Fix pub key encoding hex value not properly converted to string

README.md, src/authorization.ts, src/builders.ts, src/keys.ts, src/network.ts, src/transaction.ts, src/utils.ts, tests/src/builder-tests.ts
This PR updates the transaction builder functions to automatically fetch the account nonce from a Stacks node if a nonce is not specified. This saves a step and makes integration easier. Nonce can be set manually in the options arg.
Resolves #73
No
Readme updated.
Nonce should be fetched automatically in transaction builder when not specified via the options object.
=> Fetch nonce automatically in transaction builder

src/builders.ts
Not sure if this is intended behaviour or not, but came across a relatively unhelpful error message, while creating a ContractDeploy following the README.
The readme shows no fee in the config object, relying on the default. This causes `estimateTransfer` to be invoked:
https://github.com/blockstack/stacks-transactions-js/blob/6125026d256d44da0aff966ef82189ca30c1e7b1/src/builders.ts#L85-L87
Does fee estimation only work for TokenTransfers? This same payload check is present on `estimateContractDeploy` as well. 
https://github.com/blockstack/stacks-transactions-js/blob/6125026d256d44da0aff966ef82189ca30c1e7b1/src/builders.ts#L278-L293
Should this check be for `PayloadType.ContractDeploy` instead?
=> refactor: improve error message during fee estimation

CHANGELOG.md, README.md, src/builders.ts, src/clarity/clarityValue.ts, src/clarity/index.ts, src/clarity/serialize.ts, src/clarity/types/tupleCV.ts, src/contract-abi.ts, src/index.ts, src/network.ts, tests/src/abi-tests.ts, tests/src/abi/kv-store-abi.json, tests/src/abi/test-abi.json, tests/src/builder-tests.ts
This PR augments the `makeContractCall` transaction builder such that it fetches the contracts ABI (either from the mainne or testnet) and uses the ABI to validate that the `contract-call` payload's function arguments match the contract specification.
Issue: #3
=> Validate Contract-Call Payload with ABI

src/keys.ts, tests/src/keys-tests.ts
Creating an address from a public or private key typically involved code like:
```ts
function getAddressFromPrivateKey(privateKey: string): string {
const addrVer = addressHashModeToVersion(
AddressHashMode.SerializeP2PKH,
TransactionVersion.Testnet
);
const pubKey = pubKeyfromPrivKey(privateKey);
const addr = addressFromPublicKeys(addrVer, AddressHashMode.SerializeP2PKH, 1, [pubKey]);
const addrString = addressToString(addr);
return addrString;
}
```
Helper functions are implemented so this can be done with:
```ts
getAddressFromPrivateKey(privateKey, TransactionVersion.Testnet);
```
For details refer to issue #123
No
No
Provide context on how tests should be performed.
1. Is testing required for this change?
2. If it’s a bug fix, list steps to reproduce the bug
3. Briefly mention …
=> Helper functions for AddressFromPrivateKey and AddressFromPublicKey

CHANGELOG.md, package-lock.json, package.json, src/clarity/clarityValue.ts, src/clarity/index.ts, tests/src/clarity-tests.ts
This PR adds a function to convert TS Clarity Values to their string (source code) representation so they can be displayed easily. This is important for the Explorer.
relevant sidecar issue: https://github.com/blockstack/stacks-blockchain-sidecar/issues/99
=> Clarity Value toString function

CHANGELOG.md, src/clarity/clarityValue.ts, src/contract-abi.ts, tests/src/abi-tests.ts, tests/src/abi/test-abi.json
1. Convert an ABI function typedef to a Clarity typedef string
2. Reformat output from type -> string functions
=> Function to convert ABI function to Clarity repr string

CHANGELOG.md, src/builders.ts
This PR enables broadcasting of a serialized transaction string in a buffer.
```
const rawTx = transaction.serialize();
const url = network.getBroadcastApiUrl();
broadcastRawTransaction(rawTx, url);
```
No
No
=> Broadcast raw tx

CHANGELOG.md, package-lock.json, src/contract-abi.ts, tests/src/abi-tests.ts
This PR adds a `parseToCV` function that converts string input to the appropriate Clarity value based on the Clarity ABI type specified by the contract function. This is useful for converting user input from UI into args for contract function calls dynamically.
Example:
```
// First we need to fetch the ABI of the contract
getAbi(
contractAddress,
contractName,
txNetwork
).then((abi) => {
// Filter the function signature that we need
const filtered = abi.functions.filter(fn => fn.name === functionName);    
const expectedArgs = filtered[0].args;
const argsCV = []
// Use parseToCV() to convert to Clarity value
for (let i = 0; i < expectedArgs.length; i++) {
const expectedArg = expectedArgs[i];
const userInput = userInputs[expectedArg.name];
argsCV.push(parseToCV(userInput, …
```
=> feat: parseToCV function

jest.config.js, package-lock.json, package.json, src/contract-abi.ts, tsconfig.build.json, tsconfig.json, tsconfig.typedoc.json
When working on #87 I noticed that this project was not using our prettier config: `@blockstack/prettier-config`. This PR adds some npm tasks and runs them throughout the project. 
Nope, just code formatting
Nope.
=> fix: use blockstack prettier config

CHANGELOG.md, src/contract-abi.ts, tests/src/abi-tests.ts, tests/src/abi/test-abi.json
Allow buffers provided as contract-call arguments to be less than or equal to the size specified in the ABI.
=> fix: abi validation should allow buffers less than the specified size

.eslintrc.js, CHANGELOG.md, src/builders.ts
This fixes the contract deploy fee estimation function. Previously this was causing `makeSmartContractDeploy` fail when not specifying a fee. Also turns off `no-unnecessary-type-assertion` eslint warning.
No
No
=> Fix contract deploy fee estimation error

CHANGELOG.md, README.md, src/builders.ts, tests/src/builder-tests.ts
This PR renames the `makeSmartContractDeploy()` function to `makeContractDeploy`. 
Resolves: https://github.com/blockstack/stacks-transactions-js/issues/76
=> refactor: rename makeSmartContractDeploy for makeContractDeploy

CHANGELOG.md, src/clarity/clarityValue.ts, tests/src/clarity-tests.ts
This PR introduces a slight change to the `cvToString()` function. Uints are now serialized like `"u10"` instead of like `"10"`.
Issue: https://github.com/blockstack/stacks-blockchain/issues/1699
No
=> fix: serialize uint strings with literal u prefix

src/index.ts
Exposes a few things from `postconditions.ts`. This is used in blockstack/ux#301, which supports passing post conditions with Connect. The authenticator needs the `PostCondition` type, and client apps might need the post condition builders.
=> feat: expose PostCondition & builders

src/utils.ts, tests/src/utils-tests.ts
This helper function's repeated over a few repos. I figure this library's the most appropriate place to put it.
=> feat: add validate address helper

package.json, src/builders.ts
Ran into the slightly confusing functionality that the `broadcastTransaction` function returns the txid prequoted.
i.e. 
`"f2754bbc5d6b041d220c759b5b9b05dc0b09337959ebb725fb1ab12ac9928c3d"`
not
`f2754bbc5d6b041d220c759b5b9b05dc0b09337959ebb725fb1ab12ac9928c3d`
Any reason we specifically need `.text()` call here? I could `JSON.parse` it, of course, though unless there's a reason not to, think it's nicer to return the id directly.
Also curious if there's any reason not to have the hex encoded version with the leading `0x`? Txids returned from sidecar have this prefix and I need to compare them. 
Edit: need to use `.clone()` per this issue https://github.com/node-fetch/node-fetch/issues/533
=> fix: return response as json

CHANGELOG.md, README.md, package-lock.json, src/authorization.ts, src/builders.ts, src/errors.ts, src/keys.ts, src/signer.ts, src/transaction.ts, src/types.ts, tests/src/builder-tests.ts, tests/src/transaction-tests.ts
This PR will enable the construction of sponsored transactions where a second "sponsor" signer can pay the fees of a transaction signed by the origin. 
To create a transaction that can be sponsored, set `sponsored = true` in the transaction builder options:
```javascript
const txOptions = {
contractAddress: 'SPBMRFRPPGCDE3F384WCJPK8PQJGZ8K9QKK7F59X',
contractName: 'contract_name',
functionName: 'contract_function',
functionArgs: [bufferCVFromString('foo')],
senderKey: 'b244296d5907de9864c0b0d51f98a13c52890be0404e83f273144cd5b9960eed01',
sponsored: true,
};
const transaction = await makeContractCall(txOptions);
const serializedTx = transaction.serialize().toString('hex'); 
```
Next, pass the serialized transaction to the sponsoring party and use the `sponsorTransaction` builder function to …
=> feat: Sponsored transactions

CHANGELOG.md, src/clarity/clarityValue.ts, src/clarity/deserialize.ts, src/clarity/index.ts, src/clarity/serialize.ts, src/clarity/types/stringCV.ts, src/contract-abi.ts, tests/src/abi-tests.ts, tests/src/abi/test-abi.json, tests/src/clarity-tests.ts
This PR adds support for the new [Clarity string types](https://github.com/blockstack/stacks-blockchain/pull/1779) `string-ascii` and `string-utf8`. It does so by introducing corresponding typescript interfaces (`StringAsciiCV` and `StringUtf8CV` ), constructor functions to build them, and serialization/deserialization functions. It also adds support for validating ABIs of contracts that deal with string types.
Issue: #110 
No
=> feat: Clarity Strings

CHANGELOG.md, src/transaction.ts, tests/src/builder-tests.ts, tsconfig.build.json, tsconfig.typedoc.json
Example:
As a Blockstack developer, I must be able to interact with an API exposed by `StacksTransaction` to add a signature to an unsigned transaction.
This change is implemented with an immutable api. 
Is there a case in which spending condition would be `undefined`? Would be a lot cleaner if a tx were to always have one.
```typescript
const unsignedTx = makeUnsignedSTXTokenTransfer(txOptions);
const signedTx = unsignedTx.setSignature(sig);
```
See issue #121
=> feat: 'addSignature' method to StacksTransaction, closes #121

CHANGELOG.md, src/builders.ts, src/clarity/index.ts, src/clarity/types/optionalCV.ts, src/index.ts, src/network.ts, src/utils.ts, tests/src/builder-tests.ts
As a Blockstack developer, I would like to query the blockchain for data map entries of a contract. This is needed in the same was as read-only function calls. This pull request adds the `getMapEntry` function which uses helper methods `cvToHex` and `parseMapEntryResponse`. Both are exported as well.
For details refer to issue #126 
No, just a new feature
yes
A new test in builder-tests.js was added that calls `getMapEntry`.
=> feat: get map entry

CHANGELOG.md, src/index.ts, src/utils.ts
As a blockstack developer, I would like to use the blockstack-api-client library. The method `SmartContractsApi.callReadOnlyFunction` requires to hex encode clarity values, the result of that method needs to be parsed. In  this library (`stacks-transactions-js`) these methods already exists.
These methods, defined in `utils.ts` are now exported.
For details refer to issue #126 
No
Yes
=> feat: export cvToHex and parseReadOnlyResponse
